### ISSUE TITLE
External Providers?

### ISSUE THREAD

**Issue by marksands** [okta/okta-ios-jwt#25]
We are using B2C as our auth provider and OpenID as the protocol. Is this library usable to validate JWT signatures against?

On a whim, I threw it in our app to see if it would validate, and sure enough, it is! Though I'm a little confused as to _why_. The part that's throwing me off is when the RSA key is generated with a tag with the naming scheme  "com.okta.jwt.\(kid)". Any insight is appreciated!

**Comment by IldarAbdullin-okta** [comment]
Hi @marksands ,

Tags with the format "com.okta.jwt.(kid)" are not involved in key generation or key management. These tags are required for saving keys in iOS keychain. So this is just a primary key for the data in encrypted database.
Key generation/handling in the library doesn't have any Okta specific parts, so it is expected that the library should work with different providers that are compliant to OpenID protocol.

Does that answers your question?

Ildar
