### ISSUE TITLE
[QUESTION]: Call to loadKey in createRSAKey

### ISSUE THREAD

**Issue by antonm76** [okta/okta-ios-jwt#51]
Hello!

I'm wondering, what's the point of calling `loadKey` function in `OktaJWT.createRSAKey` (OktaJWT.swift: 234)? I do not see the purpose. For me it calls `OktaKeychain.loadKey(tag: tag)` and inside it deletes key just stored with `RSAKey.removeKeyWithTag(tag)`.
In our application it leads to the problem that key is not stored locally and as a result, when offline application cannot check whether token is expired or not.

Thanks,
Anton.

**Comment by oleggnidets-okta** [comment]
Hi @antonm76 
I guess my colleague can help us understand this code better. @IldarAbdullin-okta Could you, please, assist and explain the reason of the function `loadKey`?

**Comment by antonm76** [comment]
So, let me explain.
In our application we use OktaJWT library to work with tokens. In particular we use it to check whether token is expired or not. We discovered that when offline our routine always fails with `OktaAPIError.noWellKnown`. The reason is that `OktaJWT.getOrRetrieveKey: 185` always tries to request `wellKnown` and never is able to get `key` from the Keychain in previous call to `RSAKey.registeredKeyWithTag`.
I investigated it and discovered, that in `createRSAKey` application stores key in Keychain with `RSAKey.registerOrUpdateKey` for the `"com.okta.jwt.\(kid)"` tag, but just there deletes it from the Keychain in `loadKey` function, see `Keychain.swift: 26`.
Also, I do not see the purpose of the `OktaJWT.loadKey` function at all. It deletes stored key from the Keychain and instead stores there a tag key was stored in keychain with.

**Comment by antonm76** [comment]
@oleggnidets-okta , @IldarAbdullin-okta any update?

**Comment by oleggnidets-okta** [comment]
Hi @antonm76 
We usually don't provide estimates. Currently, this issue is recorded in our backlog, internal ref. OKTA-412123. We'll take it out in progress ASAP.

**Comment by oleggnidets-okta** [comment]
Hi @antonm76 
Could you please verify [a new release](https://github.com/okta/okta-ios-jwt/releases/tag/2.3.4)?

We rearranged validation order and introduced `offline` error.

**Comment by oleggnidets-okta** [comment]
I close the issue for now being. 
If you still have the issue, please, re-open with more details. 

Thank you for your contribution!
